"""Add global asset library tables

Revision ID: 04126958941a
Revises: 68bae7fcd569
Create Date: 2026-03-25 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = "04126958941a"
down_revision = "68bae7fcd569"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_asset",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default="[]",
        ),
        sa.Column(
            "files",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default="[]",
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default="{}",
        ),
        sa.Column(
            "style_keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default="[]",
        ),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column(
            "source_project_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column(
            "creator_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "version", sa.Integer(), nullable=False, server_default="1"
        ),
        sa.Column(
            "status",
            sa.String(length=255),
            nullable=False,
            server_default="draft",
        ),
        sa.Column(
            "thumbnail_preview_file_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column(
            "usage_count", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["source_project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thumbnail_preview_file_id"],
            ["preview_file.id"],
            name="fk_global_asset_thumbnail",
        ),
    )
    op.create_index(
        op.f("ix_global_asset_name"), "global_asset", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_global_asset_category"),
        "global_asset",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_global_asset_status"),
        "global_asset",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_global_asset_source_project_id"),
        "global_asset",
        ["source_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_global_asset_creator_id"),
        "global_asset",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        "ix_global_asset_category_status",
        "global_asset",
        ["category", "status"],
        unique=False,
    )

    op.create_table(
        "global_asset_project_link",
        sa.Column(
            "global_asset_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("linked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("global_asset_id", "project_id"),
        sa.ForeignKeyConstraint(
            ["global_asset_id"],
            ["global_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("global_asset_project_link")
    op.drop_index(
        "ix_global_asset_category_status", table_name="global_asset"
    )
    op.drop_index(
        op.f("ix_global_asset_creator_id"), table_name="global_asset"
    )
    op.drop_index(
        op.f("ix_global_asset_source_project_id"), table_name="global_asset"
    )
    op.drop_index(
        op.f("ix_global_asset_status"), table_name="global_asset"
    )
    op.drop_index(
        op.f("ix_global_asset_category"), table_name="global_asset"
    )
    op.drop_index(op.f("ix_global_asset_name"), table_name="global_asset")
    op.drop_table("global_asset")
    # ### end Alembic commands ###
